name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "bin/*"
      - ".github/workflows/*"
  pull_request:
    paths:
      - "bin/*"
      - ".github/workflows/*"

jobs:
  plugin_test:
    permissions:
      contents: read
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
        with:
          command: trufflehog --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
